name: IRIS ML Pipeline with DVC, MLflow, and CML

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write # Required for authenticating to Google Cloud

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'      
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
          create_credentials_file: true
          export_environment_variables: true
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Pull data from DVC
        run: dvc pull data -r origin --force

      - name: Train model and Log to MLflow
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: python run.py train

      - name: Run validation tests
        run: pytest test_iris_validation.py --junitxml=test-results.xml --html=test-report.html

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Generate CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# IRIS Pipeline Test Results" > report.md
          python run.py evaluate >> report.md
          cml comment create report.md

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results.xml
            test-report.html
            artifacts/
